@startuml system

  User "followings" -- "* followers" User
  (User, User) . Follower

  ToDoItem "todos" -- "1 user" User

  File "files" -- "1 user" User


  class User {
    userName: String
    password: String
    isAdmin: boolean
    isSystem: boolean
    enabled: boolean
    id: ID
  }

  class ToDoItem {
    name: String
    description: String
    done: boolean
    location: JSON
    dueToDate: Date
    published: boolean
    user: User#userName
    id: ID
  }

  class File {
    path: String
    filename: String
    mimetype: String
    encoding: String
    user: User#id
    id: ID
  }

  class Follower {
    follower: String
    following: String
    id: ID
  }

@enduml